### ISSUE TITLE
Should we pre-configure src/AppBundle?

### ISSUE THREAD

**Issue by leofeyer** [contao/standard-edition#11]
Should we pre-configure an app bundle in `src/AppBundle`? @discordier /cc

**Comment by aschempp** [comment]
Why should we do that? And what would it contain?

**Comment by leofeyer** [comment]
It would not contain anything but an empty container for the end-user to customize the application. You wanted me to add [this FIXME](https://github.com/contao/core-bundle/blob/develop/src/Resources/contao/dca/tl_templates.php#L238), therefore I figured you'd have something in mind?

**Comment by aschempp** [comment]
I don’t think we should add an AppBundle. AppBundle is for «real developers», similar as if you would create a new system/module in Contao 3. The app/Resources are for customization, similar to langconfig.php and initconfig.php

We still need to support AppBundle though as it is the new system/modules/z_custom.

**Comment by leofeyer** [comment]
How do we support it if we don't add it?

**Comment by aschempp** [comment]
What do you mean? We’re supporting translations in app/Resources but also do not ship any?

**Comment by leofeyer** [comment]
I see. By the way, I think I can remove the FIXME entry, because its related to Contao templates only and these either lie in a bundle, in a legacy module or in `/templates` but never in `src/AppBundle`, right?

**Comment by aschempp** [comment]
There sure is, in `src/AppBundle/Resources/contao/templates` …

**Comment by leofeyer** [comment]
No, because following the Symfony standards, customized templates go into `app/Resources` and not in `src/AppBundle/Resources`.

**Comment by leofeyer** [comment]
And right now, customized templates are stored in `/templates` instead of `app/Resources/contao/templates`. But we could change it of course.

**Comment by aschempp** [comment]
Yeah, but:
- Customized templates from third-party bundles (from vendor) will be in `app/Resources`
- Your custom bundle (`src/AppBundle`) can still contain its own templates for its own frontend modules

**Comment by leofeyer** [comment]
No, that's not correct according to the "Symfony best practice" book.

**Comment by aschempp** [comment]
You might be right, but it's all a bit messy to me and confusing because we're not a standard Symfony application… In Twig different bundles can have the same template name and it would still work (because of Bundle subfolders in `app/Resources`).

**Comment by discordier** [comment]
I'd rather not put empty directories (which must contain a .gitignore or the like to be present).
If end users want to build a custom app bundle, they most likely already know how to do so. If they do not know, they most likely don't want to build one.

**Comment by leofeyer** [comment]
Ok :)

**Comment by tsarma** [comment]
These kind of decisions are very much appreciate in Contao 4 documentation page. Because people tends to learn Symfony in standard installations and when they come to Contao 4, like myself, they might also get confused to see some standards folders are missing!

**Comment by discordier** [comment]
@tsarma The documentation is community maintained, feel free to file a pull request against the docs.
For details please refer to @aschempp who is responsible for merging the docs (He is on holiday for the next two weeks though).
