### ISSUE TITLE
Do not gitignore files

### ISSUE THREAD

**Issue by aschempp** [contao/standard-edition#14]
The `/files` directory is currently added to the gitignore.
https://github.com/contao/standard-edition/blob/develop/.gitignore#L6

However, this folder does certainly contain information relevant for versioning. Same applies to the `/templates` folder I guess.

**Comment by leofeyer** [comment]
It would be up to the user to adjust the file then. Otherwise the repo gets flooded with a lot of new files (I e.g. have the Contao demo installed on my dev system).

**Comment by aschempp** [comment]
I thought the distribution should contain configuration for everyone, not just for you ;-)

**Comment by leofeyer** [comment]
Indeed. And folders which are not part of the distribution should be ignored. Maybe someone else wants to rename the `/files` directory.

**Comment by aschempp** [comment]
Well if that would be true, the gitignore should ignore everything **except** the known ones… but I guess you agree that would not make sense.

**Comment by aschempp** [comment]
We discussed to keep the ignore for the following reason:
- Both directories (`files` and `templates`) are managed from the Contao backend
- Files that should be under version control should very likely not be placed in that folder(s)

For templates, they can be places in `src/AppBundle/Resources/contao/templates`. Assuming the `AppBundle` is loaded last in the `AppKernel`, any other bundle templates can be overridden.

As an example for files: You probably want to place your design files in `web/layout` and not in `web/files/layout`. They should not be manageable through the backend, but they would then be under version control.

**Comment by dmolineus** [comment]
Files outside the files folder are not accessible by the file picker and so could not be added as external CSS file.

**Comment by aschempp** [comment]
That's true, I used a custom header script tag to solve that.
