### ISSUE TITLE
Compatibility to alternative databases: Postgresql, Sqlite etc.  

### ISSUE THREAD

**Issue by hypervalley** [contao/standard-edition#15]
Do you plan to offer support for PostgreSQL and Sqlite ? There are other databases compatible with Doctrine : Oracle , MSSQL , Sybase and drizzle . Freedom to choose your database is essential for me. 
http://doctrine-dbal.readthedocs.org/en/latest/reference/platforms.html

**Comment by aschempp** [comment]
Due to the fact that we did not (yet) rewrite any of the old code, we can certainly not support other databases for a pretty long time as we need to rewrite every query…

**Comment by hypervalley** [comment]
I deduce that there is access code database that does not use Doctrine or PDO. That's right?

**Comment by aschempp** [comment]
The `contao/standard-edition` by default installs `contao/contao`, which in turn requires `contao/core-bundle`. The `core-bundle` does contain the existing Contao framework classes like [`Database`](https://github.com/contao/core-bundle/blob/develop/src/Resources/contao/library/Contao/Database.php). 

The `Database` class was turned into a bridge to Doctrine in Contao 4, but as the SQL queries are still written manually (there's no real query builder in Contao 3), some queries use MySQL-specific syntax that will not work across database systems.
