### ISSUE TITLE
Save-Buttons don't work (Text Element)

### ISSUE THREAD

**Issue by fenepedia** [contao/standard-edition#16]
I have installed contao4, latest dev.
If I create a new text element and want to save, nothing happens.

Output Browser Console:
`contao?do=article&mode=2&pid=1&rt=_hOOHSsAJ_8ux4W-U4etTB8XPYTnw7BpJRxPsXPGJPA&ref=CgVGeoS2&table=tl…:1 An invalid form control with name='text' is not focusable.`

**Comment by xchs** [comment]
See https://github.com/contao/core-bundle/issues/266
