### ISSUE TITLE
Compile Error for standard-edition on PHP 5.4.x

### ISSUE THREAD

**Issue by visionpixel** [contao/standard-edition#18]
System:
OSX Yosemite
PHP 5.4.35

If i would edit the article, it comes to the following error message:

<pre><code>Compile Error: Can't use function return value in write context
in vendor/contao/core-bundle/src/Resources/contao/classes/FrontendTemplate.php at line 188</code></pre>

Expressions support for the empty function starts in PHP 5.5.

Greetings

**Comment by leofeyer** [comment]
See https://github.com/contao/core-bundle/pull/310.
