### ISSUE TITLE
Call to a member function getParameter() on null in .../library/Contao/Config.php on line 125

### ISSUE THREAD

**Issue by RavuAlHemio** [contao/standard-edition#21]
Hello everyone,

I am having trouble getting the installation script of the Contao 4 standard edition to run on my server. It worked a couple of weeks ago but stopped recently.

Navigating to `http://mywebsite.example.com/install.php` (where `mywebsite.example.com` is the hostname of the webserver) shows the LGPL; accepting it leads to the following PHP error message:

> **Fatal error**: Call to a member function getParameter() on null in **/srv/http-mywebsite/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Config.php** on line **125**

My server's configuration:
- Arch Linux
- PHP 5.6.12
- nginx 1.8.0
- current Contao standard edition (78cfb46e73)
- [my `composer.lock`](https://gist.github.com/RavuAlHemio/21ea33d86dac91e2d9c4)

(If there is any other information I can provide, please ask!)

Thanks in advance!

**Comment by leofeyer** [comment]
Apparently, the service container has not been set. I suppose you have updated the dependencies but not the files of the standard edition?

**Comment by RavuAlHemio** [comment]
Ah, yes, performing a `composer update` seems to trigger the issue; if I revert to the standard edition's `composer.lock` and run `composer install`, the installer works again.

Which standard edition files are you referring to? I did make sure I have the newest `install.php`, and trying to add Contao to an existing Symfony installation leads to the same error message.

**Comment by leofeyer** [comment]
That's a bug. `composer update` will install version 0.9.5.1 of the installation bundle, which however only works with version 4.0.3 of the standard edition, which however has not yet been released.

You can fix this by using the following version of the `web/install.php` file: https://github.com/contao/standard-edition/blob/hotfix/4.0.3/web/install.php

**Comment by RavuAlHemio** [comment]
Oh, didn't occur to me to look through the hotfix branches. Thanks!

**Comment by leofeyer** [comment]
This is certainly not your mistake :)

**Comment by leofeyer** [comment]
I have fixed the version constraints in contao/installation-bundle@0706ef10e728317aef1ea2087db60feaef177c0b.
