### ISSUE TITLE
Enable AppCache by default

### ISSUE THREAD

**Issue by leofeyer** [contao/standard-edition#25]
As discussed on Mumble, we need to use the `AppCache` class by default and mark our routes as "not cacheable".

**Comment by aschempp** [comment]
So I looked into this, and the necessary changes are quite minimal.

All requests using the Contao `Template` class already have the correct headers:
1. on `Template::compile` the [`addToCache`](https://github.com/contao/core-bundle/blob/81cad1d2ddb0609625e2e9efc9fa97841f14633d/src/Resources/contao/classes/FrontendTemplate.php#L125-125) method is called
2. Cache time is [set to `0` by default](https://github.com/contao/core-bundle/blob/81cad1d2ddb0609625e2e9efc9fa97841f14633d/src/Resources/contao/classes/FrontendTemplate.php#L247-247) and only changed [if no backend user is logged in](https://github.com/contao/core-bundle/blob/81cad1d2ddb0609625e2e9efc9fa97841f14633d/src/Resources/contao/classes/FrontendTemplate.php#L250-250). Which means no backend content will have a cache time.
3. Then later [caching is enabled](https://github.com/contao/core-bundle/blob/81cad1d2ddb0609625e2e9efc9fa97841f14633d/src/Resources/contao/classes/FrontendTemplate.php#L320-320) if the cache time is greater zero.

The following things need to be changed in the first place:
1. enable `AppCache` like [described in the manual](http://symfony.com/doc/current/book/http_cache.html#symfony-reverse-proxy), two new lines to be added.
2. Change `Cache-Control` from `public` to `private` [in the `Template` class](https://github.com/contao/core-bundle/blob/81cad1d2ddb0609625e2e9efc9fa97841f14633d/src/Resources/contao/classes/FrontendTemplate.php#L322-322)

Setting the cache to _private_ will mean a browser will still cache it, but a (reverse) proxy must not. Actually I think this should always be the case, even in Contao 3. Our caches are for the client only, but they should not be cached by Squid or any other user proxy.

**Comment by aschempp** [comment]
Additionally, we might want to enable ESI by default: http://symfony.com/doc/current/book/http_cache.html#using-esi-in-symfony

**Comment by leofeyer** [comment]
Do you want me to make the changes or are you working on a PR?

> Cache time is set to 0 by default and only changed if no backend user is logged in. Which means no backend content will have a cache time.

What about the back end login?

**Comment by aschempp** [comment]
I can do a PR but it's rather unnecessary for two lines ^^

The backend does not have a cache time set (`$objPage->cache`) so it is never cached.

**Comment by aschempp** [comment]
> I can do a PR but it's rather unnecessary for two lines ^^

We might want to discuss it again before implementing it ;-)

**Comment by leofeyer** [comment]
Especially we should discuss this:

> Setting the cache to _private_ will mean a browser will still cache it, but a (reverse) proxy must not. Actually I think this should always be the case, even in Contao 3. Our caches are for the client only, but they should not be cached by Squid or any other user proxy.

Why should Varnish not be allowed to cache stuff? It probably will not anyway, because there are cookies and a session, but the decision should not be made be us, should it?

**Comment by aschempp** [comment]
> Why should Varnish not be allowed to cache stuff? It probably will not anyway, because there are cookies and a session, but the decision should not be made be us, should it?

Caching in Contao is always "private", because there are insert tags for the user agent string and other. We're also sending a `Vary` header which will tell to not cache based on the user, but we're telling it to ignore the cookie.

**Comment by leofeyer** [comment]
I have done a little research and you might be right.

**Comment by leofeyer** [comment]
Do I have to enable the reverse proxy in the `app_dev.php` entry point, too?

**Comment by aschempp** [comment]
I don’t think that makes sense by default. The only advantage would be potential logging, but that can be done manually if necessary.

**Comment by leofeyer** [comment]
Implemented in contao/core-bundle@a1dd774b52e8477c883631804286395c17a609d1 and d724604aa26870e6f0b4ebdd9b95ab18d1c908a1.

**Comment by aschempp** [comment]
:+1: :+1:
