### ISSUE TITLE
RC1 Release broken: No installation possible 

### ISSUE THREAD

**Issue by DanielSchwiperich** [contao/standard-edition#29]
Did test this on a local machine with Docker instances (php 5.4 and 5.9) and also to be sure it's not a faulty docker image on a clean LAMP Stack @ digitalocean

The install.php throws an  error `The installation has not been completed`
You can see it here:
http://46.101.197.71/contao4-RC1/web/install.php
A 4.0.4 version works fine to that point:
http://46.101.197.71/contao4-404/web/install.php

Some infos about the system: http://46.101.197.71/info.php

Didn't dig into this yet, no time atm. :disappointed: 
Maybe tomorrow
Not sure which component is responsible so I'd put it here. 

I saw @leofeyer did some commits on the `release/4.1.0`  branch but from the commit messages it didn't look related to this. 

If someone likes I can add _your_ ssh key to have access on that machine. Only did set up that machine for this purpose.

There is also a new dependency on `league/uri 4.0.1` which requires at least php 5.9
We can work around this with:
`composer create-project --ignore-platform-reqs contao/standard-edition <target> 4.1.0-RC1`
but error is the same like php 5.9 when trying to start installation.
The dependency thing is more `core-bundle` related because it introduced the new dependency if I'm not wrong.

**Comment by leofeyer** [comment]
See contao/core-bundle#406.

**Comment by DanielSchwiperich** [comment]
ah sorry. For sure I did look into the tickets from the core-bundle, but not at the closed ones
