### ISSUE TITLE
Symfony bekannter "src/" Ordner fehlt im Autoloader

### ISSUE THREAD

**Issue by iCodr8** [contao/standard-edition#30]
Hallo Zusammen,

mir ist bei der Entwicklung von einem Contao 4 Bundle schmerzhaft aufgefallen, dass Bundles im von Symfony bekannten "src/" Ordner nicht geladen werden.

Grund dafür ist der fehlende autoloader Code in der composer.json

``` javascript
    "autoload": {
        "psr-4": { "": "src/" },
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
    }
```

Ich gehe eigentlich davon aus, dass ihr das mit Absicht weggelassen habt, aber ich möchte nochmal nachbohren, weshalb?

Ich persönlich nutze den "src/" Ordner, wie man es eben aus Symfony kennt, zum entwickeln. Um herauszufinden, dass man dafür die composer.json anpassen muss, kostet so einiges an Zeit, was meiner Meinung nach den Entwicklern erspart werden könnte.

**Comment by leofeyer** [comment]
Wir liefern kein AppBundle mit, daher auch kein Composer-Eintrag für `src/`. Sofern der Composer-Eintrag nicht zu Problemen führt, wenn es keinen Ordner `src/` gibt, wäre ich allerdings dafür, ihn mit auszuliefern. @contao/developers Was denkt ihr?

**Comment by aschempp** [comment]
Ein Bundle muss im Kernel registriert werden, genauso wie in der composer.json. Ich finde nicht dass wir das standardmässig eintragen sollten. Ich trage jeweils auch nicht `"psr-4": { "": "src/" }` sondern `"psr-4": { "AppBundle\\": "src/AppBundle" }` ein, sonst sucht Composer alle Klassen in `/src/`.

**Comment by Toflar** [comment]
Seh ich auch so, jeder Entwickler ist selber für das Autoloading verantwortlich. Wenn man ein Bundle als Composer-Library zur Verfügung steht ist das ja auch so, wieso sollte es bei einem lokalen AppBundle anders sein?

Allerdings könnten wir die manuellen Includes für die `AppKernel` und `AppCache` weglassen. Die SF Standard Edition macht das auch so: https://github.com/symfony/symfony-standard/commit/2c4577772fd00612261bebbb22d3534efe8cca77

**Comment by leofeyer** [comment]
Das ist neu in Symfony 2.8. Beim Upgrade übernehme ich das natürlich.

**Comment by Toflar** [comment]
Wir sollten sowieso auf 2.8 upgraden, aber das wäre ein generelles `up for discussion` issue. :)

**Comment by leofeyer** [comment]
Wir sollten eigentlich auf die 3 upgraden und uns eine Lösung für das Scopes-Problem einfallen lassen.

**Comment by aschempp** [comment]
Können wir nicht, aus BC-Gründen. Die 3 hat (noch) keine Vorteile gegenüber der 2.8er.

**Comment by leofeyer** [comment]
Genau, noch nicht. Aber das bleibt nicht so und deswegen sollten wir uns eine Lösung einfallen lassen :)

**Comment by aschempp** [comment]
Lösung: Contao 5. Gehört aber nicht in dieses Ticket.

**Comment by leofeyer** [comment]
> Lösung: Contao 5.

Nein.

> Gehört aber nicht in dieses Ticket.

Ja.

**Comment by discordier** [comment]
Ich bin dagegen einen autoloader key zu liefern wenn das zugehoerige directory nicht existiert.

AFAIR hatten wir die Diskussion ob wir ein app Bundle vorkonfigurieren sollen oder nicht doch bereits vor Monaten und haben uns dagegen entschieden. die Autoloader config eines selbigen zaehlt genauso als Konfiguration.
