### ISSUE TITLE
An error is showing installing via composer

### ISSUE THREAD

**Issue by iamsarath1986** [contao/standard-edition#31]
Installing via composer an error is showing (windows 10, XAMPP, Contao 4.1.0). 

Contao\CoreBundle\Composer\ScriptHandler::generateSymlinks

  [Symfony\Component\Filesystem\Exception\IOException]
  Failed to create symbolic link from "C:\Users\user-pc\contoa/vendor/contao/core-bundle/src/Resources/contao/themes/flexible" to "C:\Users\user-pc\contoa/system/themes/flexible".

contao:symlinks

Script Contao\CoreBundle\Composer\ScriptHandler::generateSymlinks handling the post-install-cmd event terminated with an exception

  [RuntimeException]
  An error occurred while executing the "contao:symlinks" command.

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

**Comment by aschempp** [comment]
Duplicate of https://github.com/contao/core-bundle/issues/432

**Comment by iamsarath1986** [comment]
I have checked the link but it is an UBUNTU problem.

**Comment by iamsarath1986** [comment]
Is this version support windows?
