### ISSUE TITLE
Missing symlink for /files after installation

### ISSUE THREAD

**Issue by Aybee** [contao/standard-edition#33]
I installed 4.1.0 on
- Linux Debian
- Apache 2.0 Handler
- PHP Version 5.6.16

After installation I tried to put this code

``` html
<link rel="stylesheet" href="files/test.css">
```

into `Additional <head> tags` in layout. But since there's no symlink for files the test.css can not be served by the server.

I installed by uploading the download package from contao.org via FTP.

**Comment by leofeyer** [comment]
That's correct (see https://github.com/contao/core-bundle/blob/master/UPGRADE.md#protected-folders). The `files/` folder itself cannot be made public in Contao 4 anymore.
