### ISSUE TITLE
cannot be installed under PHP 5.4

### ISSUE THREAD

**Issue by fritzmg** [contao/standard-edition#37]
Right now when trying to do

```
composer create-project contao/standard-edition <target>
```

under PHP `5.4`, composer cannot install `contao/standard-edition` because some of the dependencies in the `composer.lock` file require PHP `5.5`:

```
Installing contao/standard-edition (4.1.2)
  - Installing contao/standard-edition (4.1.2)
    Loading from cache

Created project in .
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/cache v1.6.0 -> satisfiable by doctrine/cache[v1.6.0].
    - doctrine/cache v1.6.0 requires php ~5.5|~7.0 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 2
    - Installation request for doctrine/common v2.6.1 -> satisfiable by doctrine/common[v2.6.1].
    - doctrine/common v2.6.1 requires php ~5.5|~7.0 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 3
    - Installation request for league/uri 4.1.0 -> satisfiable by league/uri[4.1.0].
    - league/uri 4.1.0 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 4
    - doctrine/cache v1.6.0 requires php ~5.5|~7.0 -> your PHP version (5.4.45) does not satisfy that requirement.
    - doctrine/doctrine-cache-bundle 1.3.0 requires doctrine/cache ^1.4.2 -> satisfiable by doctrine/cache[v1.6.0].
    - Installation request for doctrine/doctrine-cache-bundle 1.3.0 -> satisfiable by doctrine/doctrine-cache-bundle[1.3.0].
```

**Comment by leofeyer** [comment]
So then just switch to PHP 5.5.

**Comment by fritzmg** [comment]
The official [documentation](https://docs.contao.org/books/manual/4.0/en/01-installation/configuring-the-live-server.html) lists PHP **5.4** as the minimum requirement for Contao 4, not PHP 5.5. That's why I reported it.

**Comment by fritzmg** [comment]
Even if you install Contao by using PHP `>=5.5` via `composer create-project contao/standard-edition <target>` - and **then** deploy the Contao installation onto another server, which happens to have only PHP `5.4`, which is the defined minimum requirement to run Contao 4, you might run into problems, since the installed versions of these bundles are not guaranteed to run under PHP `5.4`. You'll need to run a `composer update` on the new server again, to downgrade.

The `composer.lock` file of `contao/standard-edition` should be created under the minimum requirement environment, i.e. PHP `5.4.0` in this case, so that no packages with higher requirements will be present in the lock file.

**Comment by leofeyer** [comment]
> PHP 5.4, which is the defined minimum requirement to run Contao 4

The minimum PHP version for Contao 4 is 5.5 (see [composer.json](https://github.com/contao/core-bundle/blob/develop/composer.json#L13)).

**Comment by fritzmg** [comment]
> The minimum PHP version for Contao 4 is 5.5 (see composer.json).

The minimum PHP version for `contao/core-bundle` `4.1.2` is **5.4** » [composer.json](https://github.com/contao/core-bundle/blob/4.1.2/composer.json#L13)
Likewise, the minimum PHP version for `contao/standard-edition` `4.1.2` is **5.4** » [composer.json](https://github.com/contao/standard-edition/blob/4.1.2/composer.json#L13)
Also the [`composer.lock`](https://github.com/contao/standard-edition/blob/4.1.2/composer.lock) file of `contao/standard-edition` has PHP `5.4` defined as the minimum requirement for all contao bundles and components - with exception to the aforementioned packages, that lead to the error described in this issue.

Even when you specifically request `contao/standard-edition` `4.1.2`, which has PHP `5.4` as its minimum requirement, it will lead to the error described in this issue:

```
composer create-project contao/standard-edition . 4.1.2
Installing contao/standard-edition (4.1.2)
  - Installing contao/standard-edition (4.1.2)
    Loading from cache

Created project in .
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/cache v1.6.0 -> satisfiable by doctrine/cache[v1.6.0].
    - doctrine/cache v1.6.0 requires php ~5.5|~7.0 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 2
    - Installation request for doctrine/common v2.6.1 -> satisfiable by doctrine/common[v2.6.1].
    - doctrine/common v2.6.1 requires php ~5.5|~7.0 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 3
    - Installation request for league/uri 4.1.0 -> satisfiable by league/uri[4.1.0].
    - league/uri 4.1.0 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 4
    - doctrine/cache v1.6.0 requires php ~5.5|~7.0 -> your PHP version (5.4.45) does not satisfy that requirement.
    - doctrine/doctrine-cache-bundle 1.3.0 requires doctrine/cache ^1.4.2 -> satisfiable by doctrine/cache[v1.6.0].
    - Installation request for doctrine/doctrine-cache-bundle 1.3.0 -> satisfiable by doctrine/doctrine-cache-bundle[1.3.0].
```

**Comment by leofeyer** [comment]
No, it is PHP 5.5 and it always has been. We just have not update the `composer.json` file.

Contao 4 uses third-party libraries which require PHP 5.5, therefore the **implicit** minimum version was PHP 5.5 all the time. Changing the `composer.json` file only makes it an **explicit** requirement.

**Comment by fritzmg** [comment]
> No, it is PHP 5.5 and it always has been.

That's not true, Contao `4.0.x` for example has neither an _explicit_ nor an _implicit_ requirement for PHP 5.5. Thus

```
composer create-project contao/standard-edition <target> ~4.0.0
```

(and Contao itself) runs fine under PHP `5.4`. The PHP `5.5` requirement started with Contao `4.1.0-beta1` as far as I can see.

I'll make a pull request for the documentation, if needed.

**Comment by leofeyer** [comment]
I'm going to stop discussing this now. It is pointless.

**Comment by fritzmg** [comment]
? I don't understand, why is it pointless? Officially, Contao 4 still lists PHP 5.4 as its minimum requirement (I am not talking about the implicit requirement through the package management). Some users might run into this issue, if they, for some reason want to or need to run or install Contao `~4.1` under PHP 5.4.

Thus it would have been important to find out why it is not possible to install Contao 4(.1) under PHP 5.4 - and since the requirement indeed has been increased with Contao 4.1 to PHP 5.5, it would be important to reflect that change in the official documentation. Do you not agree with that :confused: ?

**Comment by aschempp** [comment]
We sure should update docs, but there's nothing we can change on Contao code side, also because PHP 5.4 is end of life and should not be used anyway.
