### ISSUE TITLE
Cron.php does not exsist

### ISSUE THREAD

**Issue by t-me** [contao/standard-edition#40]
Hello,

Yesterday i installed the latest stable contao 4 release.

I want to run a cronjob with cron.php but the file does not exsist.
there is a cron.txt in directory "web/system/cron" but not a cron.php

I have changed de settings to run with cron.php

Much Thanks

**Comment by aschempp** [comment]
The URL has changed in Contao 4 and is now `%domain%/_contao/cron`.

**Comment by t-me** [comment]
Thanks,

Maybe change the help text on 

> "genereal settings -> Disable the command scheduler"

Help tekst says : 

> Disable the periodic command scheduler and execute the cron.php script by a real cron job (which you have to set up manually)
