### ISSUE TITLE
Composer should clear the Prod-Cache too

### ISSUE THREAD

**Issue by denniserdmann** [contao/standard-edition#41]
I recently updated Contao via `composer update` and since there were bigger changes, Contao wasn't working anymore. A hint by @aschempp clearing everything in `/app/cache/` helped, but i think it's better when composer is clearing this cache too.

**Comment by leofeyer** [comment]
@contao/developers AFAIK, the `ScriptHandler::clearCache` command from the distribution bundle only clears the dev cache, doesn't it?

**Comment by aschempp** [comment]
correct, and we might want to improve that

**Comment by leofeyer** [comment]
By creating a PR for the distribution bundle?

**Comment by aschempp** [comment]
Well that's the question. The current implementation does not know about environments, and theoretically we can't know what to clear. But its obvious that only clearing one of multiple caches after a composer update does not really make sense…

**Comment by Toflar** [comment]
Imho the distribution provides a default implementation you can use. By default, it supports `dev` and `prod` so it should - by default - also consider the two environments. If somebody else introduces yet another environment, they also have to think about clearing the cache manually. Afaik composer scripts can also accept arguments so we could just add `dev` and `prod` to the global `composer.json` allowing developers to very easily extend by e.g. `test` or whatever environment name they come up with.

**Comment by aschempp** [comment]
I agree with that. Which means we should PR the option to tell the environment to clear in sension distribution bundle?

**Comment by leofeyer** [comment]
I guess so.

**Comment by leofeyer** [comment]
Also see https://github.com/sensiolabs/SensioDistributionBundle/issues/139 and https://github.com/symfony/symfony-standard/issues/679.

**Comment by leofeyer** [comment]
I have fixed this on our servers by setting `SYMFONY_ENV` to `prod`. But I don't think we can expect all hosting providers to do so.
