### ISSUE TITLE
Redirect during instalation.

### ISSUE THREAD

**Issue by wad2eq** [contao/standard-edition#43]
I'm trying install contao on localhost i put in adress bar localhost/contao/web/install.php i check box i agree with Contidion and i get  redirection do localhost/contao/install and error 404

**Comment by leofeyer** [comment]
You need to set up a document root pointing to the `/web` subfolder, so you can e.g. access the install tool via `http://contao.dev/install.php`.

**Comment by aschempp** [comment]
This is a bug I can confirm, localhost is supposed to work with web folder. But for now you can just fix the URL manually by using localhost/web/app.php/contao/install

**Comment by leofeyer** [comment]
> localhost is supposed to work with web folder

It is?

**Comment by leofeyer** [comment]
You are right. 😄

**Comment by ghost** [comment]
The issue has been moved to contao/installation-bundle#25.
