### ISSUE TITLE
@import "partial.scss" fails when using externals stylesheets in layout settings 

### ISSUE THREAD

**Issue by markocupic** [contao/standard-edition#44]
@import "bootstrap.scss" fails when using it as an externals stylesheets in the layout settings:
This is the error message in app/logs:
[2016-08-08 22:03:39] app.CRITICAL: An exception occurred. {"exception":"[object](Leafo\ScssPhp\Exception\CompilerException%28code: 0%29: Undefined variable $i: line: 48 at C:\xampp\htdocs\vendor\leafo\scssphp\src\Compiler.php:3301)"} []

The error occures when parsing this section in _grid_framework.scss on line 48:

`@include` make-col($i, $columns, $gutter);

**Comment by markocupic** [comment]
The error seems to be in bootstrap4 _grid.scss
Sorry!

**Comment by markocupic** [comment]
The error doesn't occures when using the leafo/scssphp compiler from contao 3.5.15.

**Comment by markocupic** [comment]
There is already an open issue for this error:
https://github.com/leafo/scssphp/issues/446

**Comment by leofeyer** [comment]
It does not seem as if anybody was working on the issue though, does it?

**Comment by markocupic** [comment]
Hi Leo 
I don't know. Could you reproduce the bug? 
Regards Marko

**Comment by leofeyer** [comment]
Which version of scssphp are you using?

**Comment by markocupic** [comment]
Hi Leo
The error occures, when I'm using Version 0.6.5.
When I'm using Version 0.6.3. everything works fine.

Regards Marko

**Comment by leofeyer** [comment]
There is [version 0.6.6](https://github.com/leafo/scssphp/releases) now. Can you please check if it fixes the issue?

**Comment by markocupic** [comment]
Hi Leo
Now everything works fine. It looks like the issue has been fixed in version 0.6.6.
Thank you for the support.
Marko
