### ISSUE TITLE
Incompatible with Symfony 3.2

### ISSUE THREAD

**Issue by agoat** [contao/standard-edition#47]
Contao 4 can not be installed with the new symfony 3.2!!

Currently the contao/standard-edition can be installed with composer and the current composer.lock file included in the 4.3 package. 
```
php composer create-project contao/standard-edition
```
The included composer.lock file require `symfony/symfony ~2.8|~3.0` and result in installing symfony 3.1.7. The installation works.

But when you do the following:
```
composer update
```
Composer will then update to symfony 3.2. For the moment contao continue to work BUT once you call the install component  `https:://domain.tld/contao/install` the `var/bootstrap.php.cache` will somehow be created and the total installation will crash with the following fatal error:

```
Warning: require(//cms/contao4-dev1/var/../../../../../vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php): failed to open stream: No such file or directory in //cms/contao4-dev1/var/bootstrap.php.cache on line 1792

Fatal error: require(): Failed opening required '//cms/contao4-dev1/var/../../../../../vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php' (include_path='.:/usr/local/lib/php') in //cms/contao4-dev1/var/bootstrap.php.cache on line 1792
```

This can be reverted when forcing to install Symfony 3.1.7 AND manually deleting `var/cache/*`. 

It looks like the contao/installations-bundle is not working correctly with symfony 3.2..

**Comment by agoat** [comment]
A little addition:

When accesing the contao installation in the `dev` environment (app_dev.php) it still works after calling contao/install. Only the `prod` environment crashes.

**Comment by aschempp** [comment]
Sounds like you did not clear your caches after composer update?

**Comment by agoat** [comment]
Both caches are cleared.

It happens immediately after accessing `contao/install` (exactly after the following: composer updated symfony to 3.2, clearing the prod env cache, entered the install password - Ka Woom)

**Comment by stefansl** [comment]
same here: https://github.com/contao/installation-bundle/issues/34

**Comment by fritzmg** [comment]
> Sounds like you did not clear your caches after composer update?

The error message he describes only comes _after_ you cleared the cache (at least that's what I found during testing). See also https://github.com/contao/installation-bundle/issues/34#issuecomment-264147610

**Comment by stefansl** [comment]
As a quick fix (until there is a real fix) you could disable building the bootstrap.cache.php. https://github.com/contao/installation-bundle/blob/master/src/Controller/InstallationController.php#L152

**Comment by leofeyer** [comment]
Please try to delete the `var/bootstrap.php.cache` file manually and then run `composer run-script post-update-cmd`.

**Comment by stefansl** [comment]
@leofeyer `rm app/bootstrap.php.cache && composer run-script post-update-cmd` fixes the problem temporarly. bootstrap.cache.php has **54K of code** with the following pathes at the end:
```php
...
namespace {require __DIR__.'/../vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php';}
namespace {require __DIR__.'/../vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ApcClassLoader.php';}
```
As soon as I open the install tool, this is the **entire** content in bootstrap.cache.php:
```php
<?php

 
namespace {require __DIR__.'/../../../../../vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php';}
namespace {require __DIR__.'/../../../../../vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ApcClassLoader.php';}
```

**Comment by leofeyer** [comment]
Fixed in contao/installation-bundle@1c4e59eeef4df69bdac78a1963e3351ad08d1ed3.

**Comment by aschempp** [comment]
As we removed the bootstrap file alltogether, should we also remove the composer task and package dependencies for `sensio/distribution-bundle`?

**Comment by leofeyer** [comment]
Removed in contao/installation-bundle@553cca2ad7e9c7ff319385b1f2454e239b296c7b and 645b14afb34b8747c38fdd7350837d6cacb77c9d.
