### ISSUE TITLE
Changelog shows "no changes"

### ISSUE THREAD

**Issue by hanski** [contao/standard-edition#50]
Shouldn't this changelog list the information currently found in core-bundle/changelog ?
And also, shouldn't the changelog linked in the news entry for a new release of contao/standard-edition link to this changelog?

**Comment by leofeyer** [comment]
No, because this file only documents the changes of the standard edition, not the ones of the core bundle. The core bundle has its own change log.

**Comment by hanski** [comment]
Ok, I understand the seperation.

But if the news item reads "New Contao version 4.3.3", then both the changes from the core and the standard-edition are relevant and should be presented.

Example: Update of Swiftmailer in 4.3.2 could have occured together with other changes in the core-bundle. What would the changelog show? Only changes in core-bundle? Doesn't seem right.

**Comment by leofeyer** [comment]
>  then both the changes from the core and the standard-edition are relevant

Huh? There have not been any changes in the standard edition.

**Comment by hanski** [comment]
4.3.2 - no change in core, only in SE
4.3.3 - no change in SE, only core

4.3.x - changes in both --> what now?
