### ISSUE TITLE
Wartungsmodus nicht möglich

### ISSUE THREAD

**Issue by Ainschy** [contao/standard-edition#52]
Hi,

ich habe die Zip Datei Contao 4.3.4 über contao.org geladen, auf dem Hosting entpackt und die Installation gestartet. Alles lief bis zu diesem Zeitpunkt sauber durch. 

Jedoch ließ sich der Wartungsmodus nicht aktivieren.

`Warning: fopen(/www/htdocs/XXX/webseiten/test/contao-4.3.4/app/cache/lock): failed to open stream: No such file or directory in /www/htdocs/XXX/webseiten/test/contao-4.3.4/vendor/lexik/maintenance-bundle/Drivers/FileDriver.php on line 35`

Hosting bei All-inkl.
PHP 7.1.1 über Fastcgi

**Comment by aschempp** [comment]
Seit Contao 4.3.4 ist der ZIP-Download eine Managed Edition (https://github.com/contao/managed-edition), siehe auch https://contao.org/de/news/contao-4-3-4-verfuegbar.html.

Der Fehler wird in der nächsten Contao Version bereits behoben: https://github.com/contao/manager-bundle/commit/43e63120440a271f0c14badde050f48bdbe7ce13

**Comment by Ainschy** [comment]
Ja, um den zu testen habe ich die Version installiert. 

Danke.

**Comment by Ainschy** [comment]
Was muss außer dem Eintrag in der .yml Datei noch geändert werden das es läuft?

**Comment by aschempp** [comment]
Nur den Cache leeren oder einfach var/cache löschen.

**Comment by Ainschy** [comment]
Danke das was!

**Comment by LinkingYou** [comment]
Der Fix funktioniert erst mal und die Seite geht in den Wartungsmodus.

Allerdings "springt" die Seite immer wieder automatisch aus dem Wartungsmodus, wenn man z.B. das Install-Tool aufruft. In einer Wartung kann dies aber natürlich mal notwendig sein.

Ist das Verhalten so gewünscht?
