### ISSUE TITLE
Unable to login when behind a SSL Proxy

### ISSUE THREAD

**Issue by saschlong** [contao/standard-edition#53]
Hi,

I installed the current version on a server behind a SSL proxy. For some reason I'm unable to login. It seems that the base URL is set to HTTP automatically, so the browser blocks some assets as you can see in the screenshot:

![screenshot from 2017-02-15 14-07-35](https://cloud.githubusercontent.com/assets/83601/22988776/8e4b8f2a-f3b3-11e6-94a5-840dc3b56a36.png)

**Comment by leofeyer** [comment]
Please refer to the [forums](https://community.contao.org/en/) for these kind of questions. If it turns out to be a bug in Contao, we can re-open this ticket.

**Comment by saschlong** [comment]
Did that previous to opening an issue here: https://community.contao.org/de/showthread.php?65714-Login-Probleme-mit-Contao-hinter-SSL-Proxy

IMHO it seems to be a bug, as Contao falsely thinks it is in an HTTP environment despite being accessed via HTTPS

**Comment by leofeyer** [comment]
I'm pretty sure that it is a problem with your server setup.

**Comment by saschlong** [comment]
May be. But the frontend & the install tool look and work fine (as far as the frontend goes on a fresh install).

**Comment by saschlong** [comment]
It works when I set `$_SERVER['HTTPS'] = 1;` in the `localconfig.php`. There should be an option in the install script to set that.

**Comment by aschempp** [comment]
This is a misconfiguration of your server. For whatever reason your http server (e.g. Apache) does not recognize it's https, so it's not setting the flag. This is not a Contao issue.

However, you can probably work around it by adding that to your initialize.php

**Comment by saschlong** [comment]
Thanks for the info, I'll investigate that further.

// update
The problem is afaik, that in my setup SSL ends at the proxy and then it's HTTP to Contao. As both servers are on the same machine, that is no security risk. So it isn't a misconfiguration per se and it would be cool to have an official toggle in the settings. For now the workaround works fine.
