### ISSUE TITLE
Manger Bundle in composer.json

### ISSUE THREAD

**Issue by DanielSchwiperich** [contao/standard-edition#58]
I was wondering what the reason is for having the `contao/manager-bundle` as dev dependency in the composer.json in the standard-edition?

```
   "require-dev": {
        "contao/manager-bundle": "^4.3"
    },
```

Sorry for abusing someones time if that's a stupid question but I cannot see why this was done.

**Comment by leofeyer** [comment]
The [Contao release helper](https://github.com/contao/release-helper) needs the bundle to be present in order to release a new version.

**Comment by aschempp** [comment]
🤔 does it not use the editions to create a release?

**Comment by leofeyer** [comment]
It uses the editions to pack the .zip files (`contao-release-helper build`) but not to release the bundles (`contao-release-helper release`). If you mind, I can remove the dev requirement and use a symlink instead.

**Comment by aschempp** [comment]
Personally I don't mind but I thought we removed it (using the manager-plugin) to prevent circular references?

**Comment by leofeyer** [comment]
There are no circular references. It is only a dev requirement of the root project.

**Comment by aschempp** [comment]
Well if you install dependencies for core-bundle locally, it is circular, as manager-bundle will require core-bundle again, right?

**Comment by leofeyer** [comment]
Absolutely. I have not had this problem so far though. 😄
