### ISSUE TITLE
Speichern und zurück funktioniert nicht mehr

### ISSUE THREAD

**Issue by theDyingMountain** [contao/standard-edition#59]
Die Funktion "Speichern und zurück" im Backend funktioniert nicht wie erwartet, statt dessen wird "Speichern und schließen" ausgeführt.
Fehler ist aufgetreten in der Stylesheetbearbeitung.

Erwartete Funktionalität: Speichern und Rückkehr zur Übergeordneten Seite
Resultat: Änderungen werden gespeichert, Rückkehr zur vorherigen Seite

**Comment by leofeyer** [comment]
Ich kann das Problem bei mir nicht reproduzieren.

**Comment by theDyingMountain** [comment]
Ich benutze Contao Version 4.3.5 und habe den Fehler immer.
Steps to reproduce:

1. Formatdefinition bearbeiten
2. Klick auf speichern zurück

Ich lande in den Stylesheetbearbeitung und nicht in der Stylesheetauswahl wie in Contao 3.x.x

**Comment by ghost** [comment]
Das Ticket wurde nach contao/core-bundle#870 verschoben.
