### ISSUE TITLE
Unable to clone repo.

### ISSUE THREAD

**Issue by trq** [contao/standard-edition#6]
``` sh
git clone git@github.com:contao/standard-edition.git contao
Cloning into 'contao'...
remote: Counting objects: 89907, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 89907 (delta 0), reused 0 (delta 0), pack-reused 89902
Receiving objects: 100% (89907/89907), 44.25 MiB | 412.00 KiB/s, done.
Resolving deltas: 100% (71180/71180), done.
Checking connectivity... done.
warning: remote HEAD refers to nonexistent ref, unable to checkout.
```

Leaves with with an empty contao directory.

**Comment by Toflar** [comment]
This error occurs if the default branch of a repository has been deleted on GitHub. @leofeyer: Can you make sure the default branch is `develop`?

**Comment by leofeyer** [comment]
It is. We don't have a master branch yet, therefore `develop` is the default in all new repos.

**Comment by leofeyer** [comment]
I'm confident that this issue will resolve once we have a `master` branch. For now, you can clone the repo by adding `--branch develop`:

``` bash
git clone --branch develop git@github.com:contao/standard-edition.git contao
```
