### ISSUE TITLE
Breaking change in Symfony Filesystem

### ISSUE THREAD

**Issue by loilo** [contao/standard-edition#61]
Symfony (probably unintendedly) introduced a breaking change to their Filesystem component two weeks ago.

This affects Contao's abilty to create symlinks correctly since the `makePathRelative()` method no longer works as expected.

I filed an issue over at Symfony, but we should probably track its progress here.

symfony/symfony#22328

**Comment by ausi** [comment]
Duplicate: contao/core-bundle#752

**Comment by loilo** [comment]
You guys are clearly faster than me. Great job. 🙃
