### ISSUE TITLE
Safari kann die Seite nicht öffnen, da die Netzwerkverbindung unterbrochen wurde

### ISSUE THREAD

**Issue by ghost** [contao/standard-edition#62]
Hi there
I got an error with contao/standard-edition version 4.3.7 

After installation v4.3.7 through composer (just contao and no other external plugins, etc.) I can visit the website by edge browser (windows) but not on mobile devices like iPad, iPhone (Safari browser). 

Error message "Safari kann die Seite nicht öffnen, da die Netzwerkverbindung unterbrochen wurde". And before you ask, yes my wifi works. Same error on multiple devices (iPhones).  We even try to get on the website at same time, with different devices in different places and networks. All devices shown the same error.

With version 4.2.0 everything works ok. Any clou why is this happening?

**Comment by ausi** [comment]
Can you provide a link to the affected website?
Did you take a look into the developer tools of the browser for more information about why the request was aborted?

**Comment by squidi** [comment]
Kann ich bestätigen, ist mir auch schon das eine oder andere mal aufgefallen und nicht nur in der Contao 4er, ohne dem warum und wieso weiter nach zu gehen.

**Comment by ausi** [comment]
Kannst du uns einen Link zu der betroffenen Website geben?

**Comment by squidi** [comment]
Lokale Installation, muss auch dazu sagen, das ich in der Regel OSX 10.9.5 und Safari 9.1.3 verwende, deswegen kann es auch gut daran liegen. Es tritt auch nur sporadisch auf, so das ich das nie ganz für voll genommen habe.

**Comment by ausi** [comment]
Du hast bei einer lokalen Installation im Safari die Fehlermeldung *„Safari kann die Seite nicht öffnen, da die Netzwerkverbindung unterbrochen wurde“* erhalten? Wie hast du die Website aufgerufen, `localhost`, `127.0.0.1` oder über eine lokale Domain?

**Comment by squidi** [comment]
Alle lokalen Installationen laufen über MAMP Pro

localhost:9888/contao-3/ bzw. contao4:9888/ oder auch über dyndns

Und ich meine in der Fehlermeldung stand auch was von Mehrfachweiterleitung. Da müsste ich sobald es noch mal passiert, mal konkret drauf achten.

**Comment by joke1** [comment]
Wenn der Fehler irgendwo reproduzierbar wäre, sollte einmal überprüft werden, ob der Fehler auch entsteht, wenn die Seite ohne Gzip Komprimierung ausgeliefert wird. Safari scheint damit öfters Probleme zu haben. Siehe [hier](https://forum.shopware.com/discussion/comment/199618/#Comment_199618) und [hier](https://www.google.de/search?q=gzip+safari+connection+lost).
