### ISSUE TITLE
Alias Generierung

### ISSUE THREAD

**Issue by b-fender** [contao/standard-edition#66]
Die automatische Alias-generierung von Seiten und Artikeln
wandelt Umlaute nicht mehr in 'ae, oe, ue' um und auch nicht 'ß' in 'ss', wie ich gerade festgestellt habe
in Contao 4.4.1.

Vielleicht ist das ja auch Absicht?

**Comment by leofeyer** [comment]
https://github.com/contao/core-bundle/issues/954
