### ISSUE TITLE
cacheWarmup for "setup-scripts"

### ISSUE THREAD

**Issue by rabauss** [contao/standard-edition#68]
the contao cache is not recreated with composer update/install (cache:clear without --no-warmup is deprecated since symfony 3.3)

so there should be added a script for warmup in the `"setup-scripts"` of composer.json!

see also: https://github.com/contao/installation-bundle/issues/63

**Comment by Toflar** [comment]
The managed edition does already do that. The standard edition does not provide any automated behavior whatsoever.

**Comment by leofeyer** [comment]
It seems that Symfony has not adjusted to the new behavior either:

https://github.com/symfony/symfony-standard/blob/3.3/composer.json#L37

https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Composer/ScriptHandler.php

There should be one `clearCache()` method and one `warmCache()` method IMO.

**Comment by aschempp** [comment]
That actually a Symfony/SensioLabs issue, right?

**Comment by leofeyer** [comment]
Kind of, yes.

**Comment by leofeyer** [comment]
We should probably add `"symfony-cache-warmup": true` to our `composer.json` file.

https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Composer/ScriptHandler.php#L139-L141

Alternatively we can add a separate cache warmup method, which however should be part of the `SensioDistributionBundle` rather than of Contao IMO.

**Comment by leofeyer** [comment]
> The managed edition does already do that. The standard edition does not provide any automated behavior whatsoever.

As discussed in Mumble on August 10th, 2017, we will not add a separate script handler to the standard edition unless Symfony does so as well.
