### ISSUE TITLE
Maintenance "Recreate the symlinks" fails

### ISSUE THREAD

**Issue by tonsinn** [contao/standard-edition#69]
In Contao 4.4.3 after update using Contao Manager, when I "Recreate the symlinks" I get:

Internal Server Error
What's the matter?

fopen(/tmp/sf.contao-symlinks.59a5ad6d1e94fd76fb1f72c544f6e14ac0dfe26f0441f5e81b370a382e46e65a.lock): failed to open stream: Permission denied

**Comment by leofeyer** [comment]
Please do not open multiple tickets for the same issue.

https://github.com/contao/contao-manager/issues/148
