### ISSUE TITLE
Firewall exception for routes without container scope

### ISSUE THREAD

**Issue by aschempp** [contao/standard-edition#7]
The firewall throws an exception for routes without a container scope. That's a problem because it must be possible to have routes without a scope. The firewall should check for a booted framework.

**Comment by aschempp** [comment]
After merging https://github.com/contao/core-bundle/pull/229, please remove the `_scope` attribute from the redirect route for Contao backend.

**Comment by leofeyer** [comment]
Does contao/core-bundle#229 fix this issue, too?

**Comment by aschempp** [comment]
That's what I just wrote above ;-)

**Comment by leofeyer** [comment]
Not quite …

**Comment by aschempp** [comment]
Well then, yes. The whole point of contao/core-bundle#229 is to fix this case.

**Comment by leofeyer** [comment]
Ok :)
