### ISSUE TITLE
Unattended Install

### ISSUE THREAD

**Issue by x-christian-romeni** [contao/standard-edition#70]
I was thinking about an unattended Contao installation.
The problem here: its seems like you HAVE TO interact during the composer installation ([here](https://docs.contao.org/books/manual/4.3/en/01-installation/installing-contao.html#installing-with-composer)).

Is it possible to have a -q flag or something like that, to skip these questions?

Off course the app/config/parameters.yml will be written just after the installation finishes. Before is not possible, because the folder has to be empty.

**Comment by aschempp** [comment]
Not really related to Contao, you should check out the Incenteev ParameterHandler https://github.com/Incenteev/ParameterHandler

**Comment by x-christian-romeni** [comment]
But does the setup finish when there are no parameters given? I guess not..?

**Comment by aschempp** [comment]
It depends what you want to achieve. Composer does finish, but Contao will not be able to connect to the database without credentials. But how do you intend to install/update the database?

**Comment by x-christian-romeni** [comment]
The idea is to create a completely running first installation of contao in docker.
set the parameters in a docker-compose, make it "up" and wait a few moments.
After the basic installation, have a script to copy some files and folders to the right places (eg. theme stuff).
So you can start coding right away..

-after going to /install off course..

And you are saying:
composer create-project contao/standard-edition /var/www/html 4.4.*
Will completely run through? I was thinking it will stop at the first prompt to enter database_host.

**Comment by aschempp** [comment]
I think you can use `--no-interaction` or something similar. Or just remove the composer script and create the parameters.yml on your own. I guess you'll find out by trying ;-)

**Comment by x-christian-romeni** [comment]
Yes, that looks like the right thing.. But I'm not sure if it works the right way... my /apps folder is completely empty, no files at all and no config folder. Can you confirm that?

**Comment by aschempp** [comment]
Well that depends. If you use the managed edition, the app folder is empty (except for the parameters.yml if you configure the database). The standard edition should have files in there.

**Comment by x-christian-romeni** [comment]
Its the standard edition.. and yes, it should. But it seems not.. (I have not found the time to continue testing).
