### ISSUE TITLE
cacheWarmup differences between managed-edition?

### ISSUE THREAD

**Issue by rabauss** [contao/standard-edition#71]
With the extension 'pct_customelements_plugin_customcatalog' of Premium-Contao themes, we have the problem that the cache is not warmed up correctly in the standard-edition, when we open the installer.

crazily in the managed-edition everything is fine with the cache-warmup respectively with dca copy to the cache-folder

so what are the differences between cache-warmup in standard- and managed-edition - if there are any?

**Comment by leofeyer** [comment]
You are not supposed to use the standard edition. Please use the managed edition.

**Comment by aschempp** [comment]
> so what are the differences between cache-warmup in standard- and managed-edition - if there are any?

There is none. At least none is supposed to be …

**Comment by rabauss** [comment]
I guess it's just coincidence that the extension works in the managed edition.
but the developer of the extension may take care of this.
there are obviously differences in the legacy modul loading between standard and managed edition ...

**Comment by leofeyer** [comment]
> there are obviously differences in the legacy modul loading between standard and managed edition

No, there are not – if you configure everything correctly.

The managed edition takes care of loading bundles, settings, routes, language files, DCA files, templates and everything else, which you have to configure manually in the standard edition. I assume that you forgot to add something.

Again, you are not supposed to use the standard edition for exactly these reasons.

**Comment by rabauss** [comment]
well i hope i'll get some support from pct-developers.
unfortunately the documentation for contao-standard-edition is **very very poor** for developers - but we want to have full symfony control! if you want all developers to use managed-edition, why is there a standard-edition? :-/

allthough legacy-loading with `Contao\CoreBundle\HttpKernel\Bundle\ContaoModuleBundle` worked for other extensions and was enough! so at the moment we don't understand what is missing but it's offtopic here...

**Comment by aschempp** [comment]
If you want to use the standard edition, you need to learn how Symfony works. The Contao standard edition is identical to the Symfony standard edition, except that it's pre-configured for the respective Contao core bundles.
