### ISSUE TITLE
Add default .htaccess file

### ISSUE THREAD

**Issue by aschempp** [contao/standard-edition#9]
see https://github.com/symfony/symfony-standard/blob/2.7/web/.htaccess

**Comment by leofeyer** [comment]
Nice, but we don't want to add `.htaccess` files in Contao 4. We'll add an installation guide explaining how to configure Apache or Nginx instead.

**Comment by aschempp** [comment]
That's nonsense, no user of Contao will ever be able to do that…

**Comment by leofeyer** [comment]
Copy code an paste it into an `.htaccess` file? I'm sure they will.

**Comment by leofeyer** [comment]
By the way, the documentation already exists: 

http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html

We'll only have to adjust it a bit.

**Comment by leofeyer** [comment]
I have added a reminder to our [Ahrweiler TODO list](https://github.com/contao/symfony-todo/issues/3).

**Comment by leofeyer** [comment]
As discussed on Mumble on May 20th, we want to add the default `.htaccess` file from the Symfony standard edition (`web/.htaccess`).

**Comment by leofeyer** [comment]
Added in 2b06e2a602a7aae4b7016a2a44707d92359a1510.
